version: '3.9'
services:
  db:
    image: mysql:8.0.31
    command:
      - --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: docker
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: rest-with-spring-boot-and-java
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - gusta-network
  rest-with-spring-boot-and-java:
    image: gustavoangeli/rest-with-spring-boot-and-java
    restart: always
    build: ./21_Docker
    working_dir: /21_Docker
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/rest-with-spring-boot-and-java?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: 1234
    ports:
      - 8080:8080
    command:
      - mvn spring-boot:run
    depends_on:
      - db
    networks:
      - gusta-network
networks:
  gusta-network:
    driver: bridge
